### 블로그submit: Efficient C++: 코드 사이즈 최적화
Soundlly/soundlly.github.io pull request #12
Opened 2017-11-16 01:19 UTC by jaewookkang

- title: Efficient C++: 코드 사이즈 최적화
- description: 모바일 SDK에 적용되는 C++ Native 코드 사이즈 최적화에 대해서 이야기 합니다.
- author: jwkang
- subdir: cpp-codesizeopt-jwkang

2018-02-25 06:34 UTC, pjhjohn reviewed
일단 퀵하게 리뷰합니다 ㅎㅎ

### Comments 

- 최초 작성은 더 먼저였지만, 퍼블리싱되는 날짜에 맞춰 파일명을 다시 업데이트해주셔야 #13 글보다 위에 올라갈 수 있는데요, 퍼블리싱할 날짜를 한번 정해보는게 어떨까요??
- 디렉토리명은 굳이 짧게 안써도 될 것 같아요. `cpp-code-size-optimization` 같은게 더 가독성있는 것 같은데 어떠신가요 ㅎㅎ
- **Lean C++ On Mobile**: `Learn`이 아니라 `Lean`을 사용하신게 맞죠?? 바로 읽어서는 잘 이해가 안되어서요. 그리고 `On` 같은 전치사는 소문자로 시작해주시는게 맞습니다.
- ```앱 다운로드에 데이터가 많이 소모되고, 폰안에서 많은 용량을 차지하기 때문입니다. 같은 맥락이 SDK에도 적용됩니다. 앱도 무거운 SDK 탑재를 선호 하지 않습니다. 따라서 SDK를 항상 날씬하게 유지시키는 것이 개발자들의 하나의 목표가 됩니다.```
  짧은 문장이 한 번에 너무 많은 것 같아요. 다음와 같이 재구성해보면 어떨까요??
  **다운로드에 데이터가 많이 소모되고, 용량도 많이 차지하게 되기 때문이죠. 같은 맥락으로 앱 개발자들도 무거운 SDK를 좋아하지 않습니다. 자연스레 SDK 개발자들에게는 적은 용량으로 기능을 제공하는 것이 중요한 목표가 됩니다.**
- `#include “xxxx.h”` 같은 부분은 코드 블록으로 써주시는게 좋을 것 같습니다.
- 따옴표가 2바이트 따옴표`“”`로 되어있는 경우가 많은데, 복사 - 붙여넣기하면서 자동으로 바꿔진 것 같습니다. 1바이트 따옴표`""`로 해주시면 좋을 것 같아요.
- 각 섹션이 Header + Bullet List 형태로 되어있는데, 비슷한 무게를 가진 항목들의 동등한 나열이 아니라 그냥 이야기가 진행되는 모양인데요, 이 부분은 그냥 문장으로 구성한는게 좋을 것 같아요.
- 참고 링크에서 `[label](href)` 형식으로 해주시면 좋을 것 같아요(기존 블로그 참고자료 항목 참조).

### Typos

- `무거우지게 되는 것이죠` => `무거워지게 되는 것이죠`
- `Try` `Throw` `Catch` => `try` `throw` `catch`
  (이런 키워드들은 고유명사로 해줘야할 것 같아요)

2018-02-25 06:34 UTC, pjhjohn commented on README.md
> +Note that gem may require ruby version update.
글 작성을 위한 작업과 블로그 개선을 위한 작업은 PR 단위에서 분리되는게 좋을 것 같은데요,
이런 맥락에서 Getting Started 문서는 후자에 가깝다고 생각합니다 ㅎㅎ

2018-03-25 02:38 UTC, jaewookkang commented on README.md
> +Note that gem may require ruby version update.
accept!

2018-03-25 02:51 UTC, jaewookkang commented
feedback for pjhjohn's review comments


~~최초 작성은 더 먼저였지만, 퍼블리싱되는 날짜에 맞춰 파일명을 다시 업데이트해주셔야 #13 글보다 위에 올라갈 수 있는데요, 퍼블리싱할 날짜를 한번 정해보는게 어떨까요??~~
--> accept! 업데이트 완료 2018-03-26

~~디렉토리명은 굳이 짧게 안써도 될 것 같아요. cpp-code-size-optimization 같은게 더 가독성있는 것 같은데 어떠신가요 ㅎㅎ~~
--> accept! 2018-03-26-cpp-code-size-optimization.md로 변경!

Lean C++ On Mobile: Learn이 아니라 Lean을 사용하신게 맞죠?? 바로 읽어서는 잘 이해가 안되어서요. 그리고 On 같은 전치사는 소문자로 시작해주시는게 맞습니다.
--> Lean이 맞습니다.  전치사 수정

~~앱 다운로드에 데이터가 많이 소모되고, 폰안에서 많은 용량을 차지하기 때문입니다. 같은 맥락이 SDK에도 적용됩니다. 앱도 무거운 SDK 탑재를 선호 하지 않습니다. 따라서 SDK를 항상 날씬하게 유지시키는 것이 개발자들의 하나의 목표가 됩니다.
짧은 문장이 한 번에 너무 많은 것 같아요. 다음와 같이 재구성해보면 어떨까요??
다운로드에 데이터가 많이 소모되고, 용량도 많이 차지하게 되기 때문이죠. 같은 맥락으로 앱 개발자들도 무거운 SDK를 좋아하지 않습니다. 자연스레 SDK 개발자들에게는 적은 용량으로 기능을 제공하는 것이 중요한 목표가 됩니다.~~
--> all accept! 반영!

~~#include “xxxx.h” 같은 부분은 코드 블록으로 써주시는게 좋을 것 같습니다.
따옴표가 2바이트 따옴표“”로 되어있는 경우가 많은데, 복사 - 붙여넣기하면서 자동으로 바꿔진 것 같습니다. 1바이트 따옴표""로 해주시면 좋을 것 같아요.~~
 --> accept 코드 블록으로 변경!

각 섹션이 Header + Bullet List 형태로 되어있는데, 비슷한 무게를 가진 항목들의 동등한 나열이 아니라 그냥 이야기가 진행되는 모양인데요, 이 부분은 그냥 문장으로 구성한는게 좋을 것 같아요.
참고 링크에서 [label](href) 형식으로 해주시면 좋을 것 같아요(기존 블로그 참고자료 항목 참조).

~~Typos
무거우지게 되는 것이죠 => 무거워지게 되는 것이죠
Try Throw Catch => try throw catch
(이런 키워드들은 고유명사로 해줘야할 것 같아요)~~
--> all accept 세세한 리뷰 감사!

2018-03-26 01:14 UTC, humbledude commented
수고하셨습니다.
몇 가지 제 의견 드립니다 ㅎㅎ

릴리즈 빌드를 써야 하는 이유가 추가되면 좋을까 해서 ㅎㅎㅎ
- debug symbol 을 strip 하기 때문에 용량이 작다 (pros)
- 대신 크래시가 났을때 어디서 죽었는지 찾기 어려울 수 있다. (con)

아마도, 전처리기 #define 은 코드영역으로 가지 않습니다.
이건 컴파일러 전처리기에서 다 처리한뒤 #define 들은 실제 컴파일 시에는 없어져 있는걸로 알고 있습니다.
(말 그대로 pre-processing)
전처리기를 어떻게 짰느냐에 따라 코드 사이즈의 증가 여부는 달라질꺼 같습니다.


제목은 코드 사이즈 최적화 인데,
속도 최적화 또는 기타 팁에 대한 내용도 좀 있습니다. ㅎㅎ
아래 두가지는 코드 사이즈 최적화와는 좀 다른것 같습니다.
- 워드사이즈 : 메모리 사용 최적화, cpu 아키텍쳐 최적화 (실행속도) 이야기 인거 같아요
- 예외처리 : 이거는 팁? 같이 보입니다.

2018-03-26 01:50 UTC, swka requested changes
내용 좋네요~
저는 오타 검출 위주로 리뷰 남겼습니다 ㅋㅋ @jaewookkang

2018-03-26 01:50 UTC, swka commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- 일단 컴파일러 최적화 옵션을 이용하는 것은 무족건 해야합니다. 이건 **공짜**이기 때문이죠. :-D
무족건 -> 무조건

2018-03-26 01:50 UTC, swka commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- **아직까지는 ARMv7-A를 지원해야하기 때문 하위호환성을 위해서 워드사이즈를 32비트보고 코딩을 하는 것이 좋은 선택**입니다. 따라서 double 보다는 float, long보다는 int를 사용하는 코딩이 바람직합니다.
지원해야하기 때문 -> 지원해야하기 때문에

2018-03-26 01:50 UTC, swka commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- ARMv8-A에서는 64비트 워드사이즈를 지원합니다. 갤럭시 S6쯤음 부 ARMv8 아키텍쳐가 적용되는 스마트폰은 점점 많아지기 시작됐습니다. 앞으로의 변화가 예상됩니다. 저는 pjhjohn님이 신호를 주시면 그때부터는 64비트 워드사이즈 코딩을 하려고 하고 있어요!
갤럭시 S6쯤 부터는?
적용되는 스마트폰은 -> 적용되는 스마트폰이/도

2018-03-26 01:50 UTC, swka commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +### 최적화를 위해서 일반화을 잊어라
일반화을 -> 일반화를

2018-03-26 01:50 UTC, swka commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- `try`, `throw`, `catch`문으로 구현되는 예외처리입니다. 무엇보다 로직에 구멍이나서 메모리 누수을 쉽게 야기 할수 있습니다.
메모리 누수을 -> 누수를

2018-03-26 01:54 UTC, LeeMH submitted a review, later dismissed
수고하셨습니다. 👍

2018-03-26 01:54 UTC, LeeMH commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- 효율적인 연산을 위해서는 변수크기가 워드사이즈 보다 크 경우를 피해야합니다. 그 이유는 그런 경우 연산처리를 위해서 부가적인 일을 CPU가 해야하기 때문입니다.
오타 "크" -> "큰"

2018-03-26 01:54 UTC, LeeMH commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- `try`, `throw`, `catch`문으로 구현되는 예외처리입니다. 무엇보다 로직에 구멍이나서 메모리 누수을 쉽게 야기 할수 있습니다.
이 부분은 잘 이해가 안됩니다.
예외 처리를 주의 깊게 하라는것인지? 
예외 처리가 위험하니 하지말라는 것인지?

2018-03-26 01:54 UTC, LeeMH commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +product레벨의 C++코딩을 처음으로 하게된 신입 개발자들에게는 크게 도움이 될것이라고 믿습니다.
두가지 문장이 섞여 있는것 같습니다.
"대학원에서 MATLAB/파이썬만 사용하다가 프로덕 레벨의 C++ 코딩을 시작하게 되었습니다.
C++코딩을 처음 시작하는 신입 개발자들에게 크게 도움이 될것이라고 믿습니다."

2018-03-26 08:02 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- 일단 컴파일러 최적화 옵션을 이용하는 것은 무족건 해야합니다. 이건 **공짜**이기 때문이죠. :-D
Accept

2018-03-26 08:02 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- **아직까지는 ARMv7-A를 지원해야하기 때문 하위호환성을 위해서 워드사이즈를 32비트보고 코딩을 하는 것이 좋은 선택**입니다. 따라서 double 보다는 float, long보다는 int를 사용하는 코딩이 바람직합니다.
Accept ;;

2018-03-26 08:03 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- ARMv8-A에서는 64비트 워드사이즈를 지원합니다. 갤럭시 S6쯤음 부 ARMv8 아키텍쳐가 적용되는 스마트폰은 점점 많아지기 시작됐습니다. 앞으로의 변화가 예상됩니다. 저는 pjhjohn님이 신호를 주시면 그때부터는 64비트 워드사이즈 코딩을 하려고 하고 있어요!
Accept

2018-03-26 08:04 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +### 최적화를 위해서 일반화을 잊어라
Accept

2018-03-26 08:04 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- `try`, `throw`, `catch`문으로 구현되는 예외처리입니다. 무엇보다 로직에 구멍이나서 메모리 누수을 쉽게 야기 할수 있습니다.
Accept

2018-03-26 08:05 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- 효율적인 연산을 위해서는 변수크기가 워드사이즈 보다 크 경우를 피해야합니다. 그 이유는 그런 경우 연산처리를 위해서 부가적인 일을 CPU가 해야하기 때문입니다.
Accept

2018-03-26 08:06 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +- `try`, `throw`, `catch`문으로 구현되는 예외처리입니다. 무엇보다 로직에 구멍이나서 메모리 누수을 쉽게 야기 할수 있습니다.
명시적으로 사용하지 않을 것을 추천하는 문장 추가!

2018-03-26 08:07 UTC, jaewookkang commented on _posts/2018-03-26-cpp-code-size-optimization.md
> +product레벨의 C++코딩을 처음으로 하게된 신입 개발자들에게는 크게 도움이 될것이라고 믿습니다.
"대학원에서 MATLAB/파이썬만 사용하다가" 삭제

2018-03-26 08:19 UTC, jaewookkang commented
**근희님 의견 반영사항**

1) 릴리즈 빌드를 써야 하는 이유가 추가 --> accept

2) 전처리기 #define 은 코드영역으로 가지 않습니다.이건 컴파일러 전처리기에서 다 처리한뒤 #define 들은 실제 컴파일 시에는 없어져 있는걸로 알고 있습니다 -->accept!! 좋은 코멘트 감사합니다. 하나 더 알게 됐네요 

3) 제목은 코드 사이즈 최적화 인데,속도 최적화 또는 기타 팁에 대한 내용도 좀 있습니다. 
-- accept 아래 문장 삽입
"- 따라서 워드 사이즈에 대한 최적화는 코드 사이즈 뿐만 아니라 실행 속도 최적화와도 관련이 있는 중요한 포인트 입니다."


기타 리뷰해주신 모든 분들 감사합니다. 

오타지적도 감사!

2018-03-26 08:29 UTC, swka submitted a review, later dismissed

2018-03-26 08:46 UTC, pjhjohn approved these changes

2018-03-26 09:13 UTC, swka approved these changes

2018-03-26 09:14 UTC, humbledude approved these changes

2018-03-26 09:16 UTC, LeeMH approved these changes
수고하셨습니다. 👍

2018-03-26 09:20 UTC, merged