AWS 컴퓨팅 서비스 타입 비교
Soundlly/soundlly.github.io pull request #14
Opened 2018-03-02 02:17 UTC by humbledude

리뷰 ㄱㄱ

2018-03-02 08:26 UTC, LeeMH approved these changes
깔끔하게 정리되어 있네요~

2018-03-07 04:56 UTC, pjhjohn commented
1. 첫 문단이 전부 Paragraph처리가 되어 있습니다. `typora.io` 등을 사용해서 쓰실 때, `Enter`는 문단을 나누고, `Shift + Enter`는 줄만 바꾸므로 이를 이용하시면 좋을 것 같습니다.
2. `EC2`, `ECS`, `Lambda` 등의 AWS 서비스는 해당 서비스 링크를 본문에 자연스레 넣어주면 될 것 같습니다. `[text](url)` 마크다운 문법을 사용하면 좋을 것 같습니다.
3. 텍스트가 쭈욱 쓰여있는 글이라서, 중간중간에 강조하고 싶은 부분은 볼드를 쓰면 글에 집중도가 더 있을 것 같아요.
4. **요새?** 보다는 **요새(?)**로 표현하는게 더 좋을 것 같습니다. `()`안에 넣으면 문장 구조에는 영향을 끼치지 않기 때문이에요.
5. 참고 부분의 링크들은 Unordered List (`- ...`)를 사용하면 좀 더 모여보이게 되므로 추천드립니다.
6. 맨 아래 근희님 프로필에 한마디 써주시면 좋을 것 같습니다 ㅎㅎㅎ
7. 전체적으로 **이 글을 읽게 될 사람이 나랑 어떤 공감대를 가지고 있어야 하는지(수준 / 삽질 등)** 설정해 보면 더 좋을 것 같아요!! 예를 들어 글의 서두에 **우리가 왜 이 서비스들을 조합하고 사용하게 되었는가 + Beanstalk & Lightsail 등은 왜 안썼는가** 등이 서두 혹은 말미에 조금 더 설명되면 읽는 쪽에서 몰입하기 더 좋을 것 같습니다!

[한국어 맞춤법 / 문법 검사기](speller.cs.pusan.ac.kr)로 추가로 찾아본 문법 개선안 중 위쪽 몇 개만 적어봅니다.
(고유명사 등으로 인한 오류 지적은 빼고 적어요 ㅎㅎ)
- 세가지만 => **세 가지**만
- 개발자 할일 => 개발자 **할 일**
- 어찌보면 물리 서버 한대를 쉽게 임대해서 쓰는 느낌 입니다.
  => 어**찌 보**면 물리 서버 **한 대**를 쉽게 임대해서 쓰는 **느낌입니다.**
- 분단위 => **분 단위**
- 셋팅 => **세팅**
- 다양한것을 해보고 싶을때는 => **다양한 것**을 해보고 **싶을 때는**
- 배포 해서 쓸때는 => **배포해서 쓸 때는**
- 속도때문에 => **속도 때문에**
- 생각없이 => **생각 없이**
- 쓰다보면 => **쓰다 보면**

저도 글 쓰고 한 번씩 확인해봐야 겠네요...ㄷㄷ 생각보다 저도 모르고 있던게 많네욥...
셋업 => 세트업 같은건 좀 심한 것 같긴 한데 ㅎㅎ 기본적으로 당연해보이는 것만 좀 개선해보면 좋을 것 같아요
**한 번에 300어절**만 보여주기 때문에, 글을 나눠서 두 번 정도는 돌려야 전체를 검사받을 수 있을 것 같네요

2018-03-07 05:19 UTC, pjhjohn requested changes
0. `aws-service-types` 파일명 및 디렉토리에 **비교**라는 정보가 추가되었으면 좋겠습니다.
1. 첫 문단이 전부 Paragraph처리가 되어 있습니다. `typora.io` 등을 사용해서 쓰실 때, `Enter`는 문단을 나누고, `Shift + Enter`는 줄만 바꾸므로 이를 이용하시면 좋을 것 같습니다.
2. `EC2`, `ECS`, `Lambda` 등의 AWS 서비스는 해당 서비스 링크를 본문에 자연스레 넣어주면 될 것 같습니다. `[text](url)` 마크다운 문법을 사용하면 좋을 것 같습니다.
3. 텍스트가 쭈욱 쓰여있는 글이라서, 중간중간에 강조하고 싶은 부분은 볼드를 쓰면 글에 집중도가 더 있을 것 같아요.
4. **요새?** 보다는 **요새(?)** 로 표현하는게 더 좋을 것 같습니다. `()`안에 넣으면 문장 구조에는 영향을 끼치지 않기 때문이에요.
5. 참고 부분의 링크들은 Unordered List (`- ...`)를 사용하면 좀 더 모여보이게 되므로 추천드립니다.
6. 맨 아래 근희님 프로필에 한마디 써주시면 좋을 것 같습니다 ㅎㅎㅎ
7. 전체적으로 **이 글을 읽게 될 사람이 나랑 어떤 공감대를 가지고 있어야 하는지(수준 / 삽질 등)** 설정해 보면 더 좋을 것 같아요!! 예를 들어 글의 서두에 **우리가 왜 이 서비스들을 조합하고 사용하게 되었는가 + Beanstalk & Lightsail 등은 왜 안썼는가** 등이 서두 혹은 말미에 조금 더 설명되면 읽는 쪽에서 몰입하기 더 좋을 것 같습니다!

[한국어 맞춤법 / 문법 검사기](http://speller.cs.pusan.ac.kr/PnuSpellerISAPI_201602/)로 추가로 찾아본 문법 개선안 중 위쪽 몇 개만 적어봅니다.
(고유명사 등으로 인한 오류 지적은 빼고 적어요 ㅎㅎ)
- 세가지만 => **세 가지**만
- 개발자 할일 => 개발자 **할 일**
- 어찌보면 물리 서버 한대를 쉽게 임대해서 쓰는 느낌 입니다.
  => 어**찌 보**면 물리 서버 **한 대**를 쉽게 임대해서 쓰는 **느낌입니다.**
- 분단위 => **분 단위**
- 셋팅 => **세팅**
- 다양한것을 해보고 싶을때는 => **다양한 것**을 해보고 **싶을 때는**
- 배포 해서 쓸때는 => **배포해서 쓸 때는**
- 속도때문에 => **속도 때문에**
- 생각없이 => **생각 없이**
- 쓰다보면 => **쓰다 보면**

저도 글 쓰고 한 번씩 확인해봐야 겠네요...ㄷㄷ 생각보다 저도 모르고 있던게 많네욥...
셋업 => 세트업 같은건 좀 심한 것 같긴 한데 ㅎㅎ 기본적으로 당연해보이는 것만 좀 개선해보면 좋을 것 같아요
**한 번에 300어절**만 보여주기 때문에, 글을 나눠서 두 번 정도는 돌려야 전체를 검사받을 수 있을 것 같네요

2018-03-14 06:37 UTC, humbledude commented
@pjhjohn 피드백 반영해서 수정해봤습니다.
문법 검사기는 어떻게 돌리는거에요? 링크 눌러보니까 pull request 뜨던데 ㅎㅎ

2018-03-14 06:43 UTC, pjhjohn commented
@humbledude `http://` 같은걸로 시작하지 않으니 그냥 현재 페이지에 상대경로로 붙는 것 같네요 ㅠㅠ 수정했어요!
혹시 파일명 바꾸는 작업과 본문 수정 작업을 별도의 커밋으로 나눠주실 수 있나요?? 통으로 바뀐다고 뜨니 본문 수정에 대한 리뷰를 하기가 쉽지 않을 것 같네요 ㅠㅠ

2018-03-14 07:00 UTC, humbledude commented
@pjhjohn 이번엔 힘들겠습니다... 산넘고 강을 넘었네요 ㅎㅎ
그냥 전체 한번 더 읽어주세요... ㄷㄷ

2018-03-14 07:17 UTC, pjhjohn commented
@humbledude 넵 알겠습니다 ㅎㅎ
추가로, 파일명이 바뀌면 asset이 저장되는 `subdir`도 함께 바뀌어야할 것 같습니다.

2018-03-14 08:25 UTC, humbledude commented
ㅎㅎ 다행히 asset 이 없습니다..

On 14 Mar 2018, 4:17 PM +0900, JoonHo Park <notifications@github.com>, wrote:
> @humbledude 넵 알겠습니다 ㅎㅎ
> 추가로, 파일명이 바뀌면 asset이 저장되는 subdir도 함께 바뀌어야할 것 같습니다.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-04-13 05:37 UTC, pjhjohn approved these changes
2월 21일로 되어있는데 괜찮으시죠?? ㅎㅎ

2018-04-13 05:56 UTC, LeeMH commented
의도인지 모르겠지만, 첫 시작부분이 2자 + AWS 조합이 눈에 들어오네요.

"최근에 사내" -> "최근 사내"로 바꾸면 어떤 느낌일지 쓸데없는 생각해봅니다.
"최근 보통 저는 저도 점점 처음 해서"라는 문장으로 읽혀지겠네요.

수고하셨습니다.

2018-04-17 00:29 UTC, humbledude commented
@jaewookkang @swka 리뷰 부탁 드립니다. ㅎㅎㅎㅎ

2026-02-27 08:23 UTC, closed without merging